name: Build NTRGhidra

on:
  push:
  release:
    types: created

jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
    #  contents: write
    #  packages: write
    strategy:
      matrix:
        GHIDRA_VERSION: ['11.4.2']
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin # Eclipse JDK
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Setup Ghidra
      uses: antoniovazquezblanco/setup-ghidra@master
      with:
        version: ${{ matrix.GHIDRA_VERSION }}
    - name: Build
      id: build
      run: |
        gradle
        echo "ARTIFACT=$(ls dist/*.zip)" >> "$GITHUB_ENV"
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build.outputs.ARTIFACT }}
        path: ${{ steps.build.outputs.ARTIFACT }}
        if-no-files-found: error
    - name: Release
      if: github.event_name == 'release'
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.build.outputs.ARTIFACT }}
